### ISSUE TITLE
Tetrahedral elements drawn as plates/shells

### ISSUE THREAD

**Issue by mhscott** [sewkokot/opsvis#4]
You can use the eleType command to determine if plate/shell or tetrahedral

![image](https://user-images.githubusercontent.com/13142652/143784310-dac243f0-4c46-4300-b878-222306b38cc8.png)

**Comment by sewkokot** [comment]
@mhscott Thank you for the bug report. It should be fixed now. Please check the current PyPi opsvis version. 

This is just a quick fix because I'm in the longer process of a major refactoring to make the opsvis more versatile:
1) to plot various element types in one model which is currently impossible (for example frame elements on the quad or brick mesh).
2) to plot 3d meshes (model, deformation, stress maps) with pyvista or paraview.

**Comment by mhscott** [comment]
Looks good, thanks!

![image](https://user-images.githubusercontent.com/13142652/143915852-9dcf95eb-f06c-488a-82d9-a4d579deb0e6.png)

**Comment by sewkokot** [comment]
You're welcome! Thanks for testing.

You can turn off (on by default) the labels as follows:

`opsv.plot_model(node_labels=False, element_labels=False)`

**Comment by mhscott** [comment]
Thanks! It does get a little crowded :)
